-- MySQL Script generated by MySQL Workbench
-- Tue Feb 18 10:31:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OS` DEFAULT CHARACTER SET utf8 ;
USE `OS` ;

-- -----------------------------------------------------
-- Table `OS`.`bairros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OS`.`bairros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OS`.`oss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OS`.`oss` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(255) NOT NULL,
  `inicio_prev` DATETIME NOT NULL,
  `inicio_real` DATETIME NOT NULL,
  `final_prev` DATETIME NOT NULL,
  `final_real` DATETIME NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `bairros_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_oss_bairros1_idx` (`bairros_id` ASC) VISIBLE,
  CONSTRAINT `fk_oss_bairros1`
    FOREIGN KEY (`bairros_id`)
    REFERENCES `OS`.`bairros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OS`.`equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OS`.`equipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `func_lider_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipes_funcionarios1_idx` (`func_lider_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipes_funcionarios1`
    FOREIGN KEY (`func_lider_id`)
    REFERENCES `OS`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OS`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OS`.`funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `valorhora` DECIMAL(6,2) NOT NULL,
  `equipes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionarios_equipes_idx` (`equipes_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_equipes`
    FOREIGN KEY (`equipes_id`)
    REFERENCES `OS`.`equipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OS`.`oss_equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OS`.`oss_equipes` (
  `os_id` INT NOT NULL,
  `equipes_id` INT NOT NULL,
  PRIMARY KEY (`os_id`, `equipes_id`),
  INDEX `fk_os_has_equipes_equipes1_idx` (`equipes_id` ASC) VISIBLE,
  INDEX `fk_os_has_equipes_os1_idx` (`os_id` ASC) VISIBLE,
  CONSTRAINT `fk_os_has_equipes_os1`
    FOREIGN KEY (`os_id`)
    REFERENCES `OS`.`oss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_has_equipes_equipes1`
    FOREIGN KEY (`equipes_id`)
    REFERENCES `OS`.`equipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
